# Generated by Django 3.2.9 on 2021-12-02 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=20)),
                ('age_group', models.CharField(choices=[('1', '0-10'), ('2', '10-20'), ('3', '20-30'), ('4', '30-40'), ('5', '40-50'), ('6', '50-60'), ('7', '60-70')], default='1', max_length=10)),
                ('reg_month', models.CharField(choices=[('january', 'January'), ('february', 'February'), ('march', 'March'), ('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'Septemder'), ('october', 'October'), ('november', 'November'), ('december', 'December')], default='january', max_length=200)),
                ('health_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.healthfacility')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.location')),
            ],
        ),
        migrations.AddField(
            model_name='healthfacility',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.location'),
        ),
    ]
